version: "3"

services:

  gateway:
    image: kong
    restart: always
    ports:
      - 90:8000
      - 91:8001
    volumes:
      - ${PWD}/devops:/home/kong
    depends_on:
      - kollector
    links:
      - kollector:kollector
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/home/kong/kong.yml"
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    env_file:
      - ../.env

  kollector:
    image: kollector
    build:
      context: ../
      dockerfile: ./devops/kollector.dockerfile
    command:
      - kollector
      - "-p"
      - btcusdt,ethbtc,ltcbtc,xrpbtc
    ports:
      - 8050:8050
    environment:
      APP_GRPC_HOST: "0.0.0.0"

  kollector-web:
    image: kollector-web
    build:
      context: ../
      dockerfile: ./devops/web.dockerfile
    ports:
      - 4000:3000
