version: "3"

services:

  gateway:
    image: kong
    restart: always
    ports:
      - 90:8000
      - 91:8001
    volumes:
      - ${PWD}/devops:/home/kong
    depends_on:
      - kollector
    links:
      - kollector:kollector
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/home/kong/kong.yml"
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    env_file:
      - ../.env

  kollector:
    image: kollector
    build: ../
    command:
      - kollector
      - "-p"
      - ethbtc
    ports:
      - 8050:8050
    environment:
      APP_GRPC_HOST: "0.0.0.0"
